#!/usr/bin/env python3


from src import main


if __name__ == '__main__':
    while True:
        try: 
            main.SherlockSight(main.args)

            break
        except KeyboardInterrupt:
            if args.verbose:
                print("Process interrupted with Ctrl + C")

                break
            break
        except Exception as e:
            if args.verbose:
                print("Error : {}".format(str(e))) 

    if main.args.verbose:
        print("Stopped in {} seconds".format(datetime.now() - main.start_time))

